---
kind: Service
apiVersion: v1
metadata:
  name: beejee-test-app
spec:
  type: LoadBalancer
  selector:
    app: beejee-test-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beejee-test-app
spec:
  selector:
    matchLabels:
      app: beejee-test-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: beejee-test-app
    spec:
      containers:
      - name: beejee-test-app
        image: unitedt/beejee-test-app:latest
        imagePullPolicy: Always
        env:
          - name: APP_ROOT_URI
            value: "http://157.230.76.133"
          - name: DB_NAME
            value: "beejee_test"
          - name: DB_USER
            value: "doadmin"
          - name: DB_PASSWORD
            value: "d3iggh62toojdayt"
          - name: DB_HOST
            value: "private-db-mysql-fra1-one-do-user-7647016-0.a.db.ondigitalocean.com"
          - name: DB_PORT
            value: "25060"
        ports:
        - containerPort: 8080
          protocol: TCP
