apiVersion: v1
kind: Service
metadata:
  name: beejee-test-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: beejee-test-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: beejee-test-app
  labels:
    app: beejee-test-app
spec:
  selector:
    matchLabels:
      app: beejee-test-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: beejee-test-app
    spec:
      containers:
      - image: unitedt/beejee-test-app
        imagePullPolicy: Always
        name: beejee-test-app
        env:
          - name: APP_ROOT_URI
            value: ""
          - name: DB_NAME
            value: "beejee_test"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "r56t"
          - name: DB_HOST
            value: "172.17.0.1"
          - name: DB_PORT
            value: "3307"
        ports:
          - containerPort: 8080
